version: "3.11"

services:

  http-balancer:
    image: nginx:1.25.4-alpine
    ports:
    - "80:80"
    volumes:
    - "./coworkingspace/static:/var/www/static"
    - "./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - backend-1

  database:
    image: postgres:16.2
    restart: always
    env_file:
      - compose/.database_compose.env

    ports:
      - "5433:5432"

    volumes:
      - "./compose/pg_data:/var/lib/postgresql/data"


  backend-1:
    image: coworkingspace:0.1
    restart: always
    build: .
    command: /app/run.sh
#poetry run python coworkingspace/manage.py runserver 0.0.0.0:8000
    env_file:
      - compose/.compose.env
    depends_on:
      - database
    volumes:
      - "./coworkingspace/static:/app/coworkingspace/static"
      - "./coworkingspace/app:/app/coworkingspace/app"
      - "./coworkingspace/users:/app/coworkingspace/users"
      - "./coworkingspace/coworkingspace:/app/coworkingspace/coworkingspace"
      - "./coworkingspace/templates:/app/coworkingspace/templates"
