# Generated by Django 5.0.4 on 2024-04-24 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AddField(
            model_name='userscoworking',
            name='places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_cooworking', to='app.placecoworking', verbose_name='Номер место ковореинга'),
        ),
        migrations.AddField(
            model_name='userscoworking',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_cooworking', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AddField(
            model_name='userreview',
            name='coworking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userscoworking'),
        ),
        migrations.AddIndex(
            model_name='userscoworking',
            index=models.Index(fields=['meeting_time'], name='meeting_time_index'),
        ),
        migrations.AlterUniqueTogether(
            name='userscoworking',
            unique_together={('users', 'places', 'meeting_time')},
        ),
        migrations.AddIndex(
            model_name='userreview',
            index=models.Index(fields=['created_at'], name='created_at_index'),
        ),
    ]
