# Generated by Django 5.0.4 on 2024-04-23 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userreview',
            name='coworking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userscoworking'),
        ),
    ]
