# Generated by Django 5.0.4 on 2024-04-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userreview_id_alter_userreview_coworking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='id',
        ),
        migrations.AlterField(
            model_name='userreview',
            name='coworking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.userscoworking'),
        ),
    ]
